import type { Metadata } from "next";
import "@/public/globals.css";
import AppProvider from "./app-provider";
import NavContainer from "../server-components/nav-container/nav-container.component";

export const metadata: Metadata = {
  title: "Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <AppProvider>
          <div style={{
            position: 'absolute',
            top: 0,
            width: '100%',
            zIndex: 999,
          }}>
            <NavContainer />
          </div>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
