import type { Metadata } from "next";
import "@/public/globals.css";
import AppProvider from "./app-provider";

export const metadata: Metadata = {
  title: "Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
